language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install pytest pytest-cov
  - pip install -e .

script:
  - pytest --verbose --cov-report term --cov=escraper/

after_success:
  - bash <(curl -s https://codecov.io/bash)
